---

name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "10 0 * * 3"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: docker build -t docker-ansible .

      - name: Run the built image.
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-ansible

      - name: Verify Ansible is accessible in the built image.
        run: docker exec --tty test-container env TERM=xterm ansible --version

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
        
    # - name: Build container image
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{github.actor}}
    #     password: ${{secrets.GITHUB_TOKEN}}
    #     registry: ghcr.io
    #     repository: tonyskidmore/ci-ubuntu2004-ansible/ci-ubuntu2004-ansible
    #     tag_with_sha: true

    - name: Show env
      run: env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      uses: docker/build-push-action@v2
      with:
        tags: |
          ghcr.io/tonyskidmore/ci-ubuntu2004-ansible:latest
        file: /Dockerfile
        # build-args: APP_VERSION_ARG=${{ github.event.release.tag_name }}
        # ghcr.io/tonyskidmore/ci-ubuntu2004-ansible:${{ github.event.release.tag_name }}
        push: true

